config/routes.rb
CycleTracker::Application.routes.draw do
  
  get "welcome/index"
  resources :biometrics
  resources :moods
  resources :sleeps
  resources :weight_trainings
  resources :strength_trainings
  resources :weight_trainnings
  resources :stairs
  resources :rides
  resources :recents
  resources :routines
 devise_for :users
  root to: 'welcome#index'

  
end

app/models/biometric.rb
class Biometric < ActiveRecord::Base
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :exercise_type
  belongs_to :routine
end

app/models/exercise_type.rb
class ExerciseType < ActiveRecord::Base
  has_many :exercises
end

app/models/mood.rb
class Mood < ActiveRecord::Base
end

app/models/recent.rb
class Recent < ActiveRecord::Base
  #attr_accessible :user_id
  #belongs_to :user
end

app/models/ride.rb
class Ride < ActiveRecord::Base
end

app/models/routine.rb
class Routine < ActiveRecord::Base
  has_many :exercises
end

app/models/sleep.rb
class Sleep < ActiveRecord::Base
end

app/models/stair.rb
class Stair < ActiveRecord::Base
end

app/models/strength_training.rb
class StrengthTraining < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
    #attr_accessible :email, :password, :password_confirmation, :remember_me,
    #:first_name, :last_name, :profile_name
end

app/models/weight_training.rb
class WeightTraining < ActiveRecord::Base
end

app/models/weight_trainning.rb
class WeightTrainning < ActiveRecord::Base
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: [:show, :edit, :update, :destroy]

  # GET /moods
  # GET /moods.json
  def index
    @moods = Mood.all
  end

  # GET /moods/1
  # GET /moods/1.json
  def show
  end

  # GET /moods/new
  def new
    @mood = Mood.new
  end

  # GET /moods/1/edit
  def edit
  end

  # POST /moods
  # POST /moods.json
  def create
    @mood = Mood.new(mood_params)

    respond_to do |format|
      if @mood.save
        format.html { redirect_to @mood, notice: 'Mood was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mood }
      else
        format.html { render action: 'new' }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moods/1
  # PATCH/PUT /moods/1.json
  def update
    respond_to do |format|
      if @mood.update(mood_params)
        format.html { redirect_to @mood, notice: 'Mood was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moods/1
  # DELETE /moods/1.json
  def destroy
    @mood.destroy
    respond_to do |format|
      format.html { redirect_to moods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = Mood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mood_params
      params.require(:mood).permit(:date, :feeling, :note)
    end
end

app/controllers/recents_controller.rb
class RecentsController < ApplicationController
  before_action :set_recent, only: [:show, :edit, :update, :destroy]

  # GET /recents
  # GET /recents.json
  def index
    @recents = Recent.all
  end

  # GET /recents/1
  # GET /recents/1.json
  def show
  end

  # GET /recents/new
  def new
    @recent = Recent.new
  end

  # GET /recents/1/edit
  def edit
  end

  # POST /recents
  # POST /recents.json
  def create
    @recent = Recent.new(recent_params)

    respond_to do |format|
      if @recent.save
        format.html { redirect_to @recent, notice: 'Recent was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recent }
      else
        format.html { render action: 'new' }
        format.json { render json: @recent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recents/1
  # PATCH/PUT /recents/1.json
  def update
    respond_to do |format|
      if @recent.update(recent_params)
        format.html { redirect_to @recent, notice: 'Recent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recents/1
  # DELETE /recents/1.json
  def destroy
    @recent.destroy
    respond_to do |format|
      format.html { redirect_to recents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recent
      @recent = Recent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recent_params
      params.require(:recent).permit(:ride, :Date, :route, :ride, :time, :distance, :average, :speed, :fastest, :speed, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biometrics_helper.rb
module BiometricsHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/recents_helper.rb
module RecentsHelper
  
  def total_distance 
    distances = @recents.map &:distance
    distances.inject :+
  end
  
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sleeps_helper.rb
module SleepsHelper
end

app/helpers/stairs_helper.rb
module StairsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/recents/_form.html.erb
<%= form_for(@recent, html: {class: "form-vertical"}) do |f| %>
  <% if @recent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recent.errors.count, "error") %> prohibited this recent from being saved:</h2>

      <ul>
      <% @recent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>

  <div class="field">
    <%= f.label :Date %><br>
    <%= f.date_select :Date %>
  </div>
  <div class="field">
    <%= f.label :Route %><br>
    <%= f.text_field :route %>
  </div>
  
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :average %><br>
    <%= f.text_field :average %>
  </div>
  
  <div class="field">
    <%= f.label :fastest %><br>
    <%= f.text_field :fastest %>
  </div>
  

  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="form-actions">
	
    <%= f.submit %>

  </div>
<% end %>

app/views/recents/edit.html.erb
<h4>Editing recent</h4>

<%= render 'form' %>

<%= link_to 'Show', @recent %> |
<%= link_to 'Back', recents_path %>

app/views/recents/index.html.erb
<div class="page-header">
	<h4>Cycling</h4>

<button type="button"class="btn">
<%= link_to 'Add New Ride', new_recent_path %>
</button>

<!--
<% @recents.each do |recent| %>
<div class="recents">
	<div class="date">Date: <%= recent.Date %> </div>
	<div class="distance">Distance:<%=link_to recent.distance, recent%></div>
    <div class="meta">
		<span><%= recent.Date %></span>
        <span><%= recent.route %><span>
        <%= recent.time %>
        <%= recent.distance %>
        <%= recent.average %>
        <%= recent.fastest %>
        <%= recent.notes %>
	
	</div>
	<span class="admin">
		<%= link_to "Edit", edit_recent_path(recent) %> |
		<%= link_to "Delete", recent, method: :delete, data: {confirm: "Are you sure you want to delete this entry?"}%>
	</span>
</div>

<% end %>
-->



<table class="table">
  <thead>
    <tr>
      
      <th>Date</th>
      <th>Route</th>
      <th>Time</th>
      <th>Distance</th>
      <th>Av.Speed</th>
      <th>Fastest</th>
      <th>Notes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recents.each do |recent| %>
      <tr>
        
        <td><%= recent.Date %></td>
        <td><%= recent.route %></td>
        <td><%= recent.time %></td>
        <td><%= recent.distance %></td>
        <td><%= recent.average %></td>
        <td><%= recent.fastest %></td>
        <td><%= recent.notes %></td>
        <td><%= link_to 'Show', recent %></td>
        <td><%= link_to 'Edit', edit_recent_path(recent) %></td>
        <td><%= link_to 'Delete', recent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
	<tr>
        
        <td></td>
        <td>Total</td>
        <td></td>
        <td><%= total_distance %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
  </tbody>
</table>

<br>

app/views/recents/new.html.erb
<h1>New recent</h1>

<%= render 'form' %>

<%= link_to 'Back', recents_path %>

app/views/recents/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Date:</strong>
  <%= @recent.Date %>
</p>

<p>
  <strong>Route:</strong>
  <%= @recent.route %>
</p>



<p>
  <strong>Time:</strong>
  <%= @recent.time %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @recent.distance %>
</p>

<p>
  <strong>Average:</strong>
  <%= @recent.average %>
</p>


<p>
  <strong>Fastest:</strong>
  <%= @recent.fastest %>
</p>


<p>
  <strong>Notes:</strong>
  <%= @recent.notes %>
</p>

<%= link_to 'Edit', edit_recent_path(@recent) %> |
<%= link_to 'Back', recents_path %>