config/routes.rb
CycleTracker::Application.routes.draw do
  
  get "welcome/index"
  resources :biometrics
  resources :moods
  resources :sleeps
  resources :weight_trainings
  resources :strength_trainings
  resources :weight_trainnings
  resources :stairs
  resources :rides
  resources :recents
  resources :routines
 devise_for :users
  root to: 'welcome#index'

  
end

app/models/biometric.rb
class Biometric < ActiveRecord::Base
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :exercise_type
  belongs_to :routine
end

app/models/exercise_type.rb
class ExerciseType < ActiveRecord::Base
  has_many :exercises
end

app/models/mood.rb
class Mood < ActiveRecord::Base
end

app/models/recent.rb
class Recent < ActiveRecord::Base
  #attr_accessible :user_id
  #belongs_to :user
end

app/models/ride.rb
class Ride < ActiveRecord::Base
end

app/models/routine.rb
class Routine < ActiveRecord::Base
  has_many :exercises
end

app/models/sleep.rb
class Sleep < ActiveRecord::Base
end

app/models/stair.rb
class Stair < ActiveRecord::Base
end

app/models/strength_training.rb
class StrengthTraining < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
    #attr_accessible :email, :password, :password_confirmation, :remember_me,
    #:first_name, :last_name, :profile_name
end

app/models/weight_training.rb
class WeightTraining < ActiveRecord::Base
end

app/models/weight_trainning.rb
class WeightTrainning < ActiveRecord::Base
end

app/controllers/weight_trainings_controller.rb
class WeightTrainingsController < ApplicationController
  before_action :set_weight_training, only: [:show, :edit, :update, :destroy]

  # GET /weight_trainings
  # GET /weight_trainings.json
  def index
    @weight_trainings = WeightTraining.all
  end

  # GET /weight_trainings/1
  # GET /weight_trainings/1.json
  def show
  end

  # GET /weight_trainings/new
  def new
    @weight_training = WeightTraining.new
    @exercise_types = ExerciseType.all
  end

  # GET /weight_trainings/1/edit
  def edit
  end

  # POST /weight_trainings
  # POST /weight_trainings.json
  def create
    @weight_training = WeightTraining.new(weight_training_params)

    respond_to do |format|
      if @weight_training.save
        format.html { redirect_to @weight_training, notice: 'Weight training was successfully created.' }
        format.json { render action: 'show', status: :created, location: @weight_training }
      else
        format.html { render action: 'new' }
        format.json { render json: @weight_training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weight_trainings/1
  # PATCH/PUT /weight_trainings/1.json
  def update
    respond_to do |format|
      if @weight_training.update(weight_training_params)
        format.html { redirect_to @weight_training, notice: 'Weight training was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @weight_training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weight_trainings/1
  # DELETE /weight_trainings/1.json
  def destroy
    @weight_training.destroy
    respond_to do |format|
      format.html { redirect_to weight_trainings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight_training
      @weight_training = WeightTraining.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weight_training_params
      params.require(:weight_training).permit(:date, :push_up, :sit_up, :toe_raise, :squat, :leg_extension, :curl, :tricep_exstension, :should_press, :lat_pulldown, :bench_press, :seated_row, :peck_fly)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biometrics_helper.rb
module BiometricsHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/recents_helper.rb
module RecentsHelper
  
  def total_distance 
    distances = @recents.map &:distance
    distances.inject :+
  end
  
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sleeps_helper.rb
module SleepsHelper
end

app/helpers/stairs_helper.rb
module StairsHelper
end

app/helpers/weight_trainings_helper.rb
module WeightTrainingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/weight_trainings/_form.html.erb
<%= simple_form_for(@weight_training) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :date %>
    <% @exercise_types.each do |exercise_type| %>
	  <%= f.input exercise_type.name %>
	<% end %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/weight_trainings/edit.html.erb
<h1>Editing weight_training</h1>

<%= render 'form' %>

<%= link_to 'Show', @weight_training %> |
<%= link_to 'Back', weight_trainings_path %>

app/views/weight_trainings/index.html.erb
<h4>Weight Training</h4>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Push up</th>
      <th>Sit up</th>
      <th>Toe raise</th>
      <th>Squat</th>
      <th>Leg extension</th>
      <th>Curl</th>
      <th>Tricep exstension</th>
      <th>Should press</th>
      <th>Lat pulldown</th>
      <th>Bench press</th>
      <th>Seated row</th>
      <th>Peck fly</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @weight_trainings.each do |weight_training| %>
      <tr>
        <td><%= weight_training.date %></td>
        <td><%= weight_training.push_up %></td>
        <td><%= weight_training.sit_up %></td>
        <td><%= weight_training.toe_raise %></td>
        <td><%= weight_training.squat %></td>
        <td><%= weight_training.leg_extension %></td>
        <td><%= weight_training.curl %></td>
        <td><%= weight_training.tricep_exstension %></td>
        <td><%= weight_training.should_press %></td>
        <td><%= weight_training.lat_pulldown %></td>
        <td><%= weight_training.bench_press %></td>
        <td><%= weight_training.seated_row %></td>
        <td><%= weight_training.peck_fly %></td>
        <td><%= link_to 'Show', weight_training %></td>
        <td><%= link_to 'Edit', edit_weight_training_path(weight_training) %></td>
        <td><%= link_to 'Destroy', weight_training, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button class="btn">
<%= link_to 'New weight training', new_weight_training_path %>
</button>

app/views/weight_trainings/new.html.erb
<h1>New weight_training</h1>

<%= render 'form' %>

<%= link_to 'Back', weight_trainings_path %>

app/views/weight_trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @weight_training.date %>
</p>

<p>
  <strong>Push up:</strong>
  <%= @weight_training.push_up %>
</p>

<p>
  <strong>Sit up:</strong>
  <%= @weight_training.sit_up %>
</p>

<p>
  <strong>Toe raise:</strong>
  <%= @weight_training.toe_raise %>
</p>

<p>
  <strong>Squat:</strong>
  <%= @weight_training.squat %>
</p>

<p>
  <strong>Leg extension:</strong>
  <%= @weight_training.leg_extension %>
</p>

<p>
  <strong>Curl:</strong>
  <%= @weight_training.curl %>
</p>

<p>
  <strong>Tricep exstension:</strong>
  <%= @weight_training.tricep_exstension %>
</p>

<p>
  <strong>Should press:</strong>
  <%= @weight_training.should_press %>
</p>

<p>
  <strong>Lat pulldown:</strong>
  <%= @weight_training.lat_pulldown %>
</p>

<p>
  <strong>Bench press:</strong>
  <%= @weight_training.bench_press %>
</p>

<p>
  <strong>Seated row:</strong>
  <%= @weight_training.seated_row %>
</p>

<p>
  <strong>Peck fly:</strong>
  <%= @weight_training.peck_fly %>
</p>

<%= link_to 'Edit', edit_weight_training_path(@weight_training) %> |
<%= link_to 'Back', weight_trainings_path %>