config/routes.rb
CycleTracker::Application.routes.draw do
  
  get "welcome/index"
  resources :biometrics
  resources :moods
  resources :sleeps
  resources :weight_trainings
  resources :strength_trainings
  resources :weight_trainnings
  resources :stairs
  resources :rides
  resources :recents
  resources :routines
 devise_for :users
  root to: 'welcome#index'

  
end

app/models/biometric.rb
class Biometric < ActiveRecord::Base
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :exercise_type
  belongs_to :routine
end

app/models/exercise_type.rb
class ExerciseType < ActiveRecord::Base
  has_many :exercises
end

app/models/mood.rb
class Mood < ActiveRecord::Base
end

app/models/recent.rb
class Recent < ActiveRecord::Base
  #attr_accessible :user_id
  #belongs_to :user
end

app/models/ride.rb
class Ride < ActiveRecord::Base
end

app/models/routine.rb
class Routine < ActiveRecord::Base
  has_many :exercises
end

app/models/sleep.rb
class Sleep < ActiveRecord::Base
end

app/models/stair.rb
class Stair < ActiveRecord::Base
end

app/models/strength_training.rb
class StrengthTraining < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
    #attr_accessible :email, :password, :password_confirmation, :remember_me,
    #:first_name, :last_name, :profile_name
end

app/models/weight_training.rb
class WeightTraining < ActiveRecord::Base
end

app/models/weight_trainning.rb
class WeightTrainning < ActiveRecord::Base
end

app/controllers/biometrics_controller.rb
class BiometricsController < ApplicationController
  before_action :set_biometric, only: [:show, :edit, :update, :destroy]

  # GET /biometrics
  # GET /biometrics.json
  def index
    @biometrics = Biometric.all
  end

  # GET /biometrics/1
  # GET /biometrics/1.json
  def show
  end

  # GET /biometrics/new
  def new
    @biometric = Biometric.new
  end

  # GET /biometrics/1/edit
  def edit
  end

  # POST /biometrics
  # POST /biometrics.json
  def create
    @biometric = Biometric.new(biometric_params)

    respond_to do |format|
      if @biometric.save
        format.html { redirect_to @biometric, notice: 'Biometric was successfully created.' }
        format.json { render action: 'show', status: :created, location: @biometric }
      else
        format.html { render action: 'new' }
        format.json { render json: @biometric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biometrics/1
  # PATCH/PUT /biometrics/1.json
  def update
    respond_to do |format|
      if @biometric.update(biometric_params)
        format.html { redirect_to @biometric, notice: 'Biometric was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @biometric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biometrics/1
  # DELETE /biometrics/1.json
  def destroy
    @biometric.destroy
    respond_to do |format|
      format.html { redirect_to biometrics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biometric
      @biometric = Biometric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def biometric_params
      params.require(:biometric).permit(:date, :weight, :bmi, :note, :time)
    end
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: [:show, :edit, :update, :destroy]

  # GET /moods
  # GET /moods.json
  def index
    @moods = Mood.all
  end

  # GET /moods/1
  # GET /moods/1.json
  def show
  end

  # GET /moods/new
  def new
    @mood = Mood.new
  end

  # GET /moods/1/edit
  def edit
  end

  # POST /moods
  # POST /moods.json
  def create
    @mood = Mood.new(mood_params)

    respond_to do |format|
      if @mood.save
        format.html { redirect_to @mood, notice: 'Mood was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mood }
      else
        format.html { render action: 'new' }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moods/1
  # PATCH/PUT /moods/1.json
  def update
    respond_to do |format|
      if @mood.update(mood_params)
        format.html { redirect_to @mood, notice: 'Mood was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moods/1
  # DELETE /moods/1.json
  def destroy
    @mood.destroy
    respond_to do |format|
      format.html { redirect_to moods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = Mood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mood_params
      params.require(:mood).permit(:date, :feeling, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biometrics_helper.rb
module BiometricsHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/recents_helper.rb
module RecentsHelper
  
  def total_distance 
    distances = @recents.map &:distance
    distances.inject :+
  end
  
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sleeps_helper.rb
module SleepsHelper
end

app/helpers/stairs_helper.rb
module StairsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/biometrics/_form.html.erb
<%= simple_form_for(@biometric) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :date %>
    <%= f.input :weight %>
    <%= f.input :bmi %>
    <%= f.input :note %>
    <%= f.input :time %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/biometrics/edit.html.erb
<h1>Editing biometric</h1>

<%= render 'form' %>

<%= link_to 'Show', @biometric %> |
<%= link_to 'Back', biometrics_path %>

app/views/biometrics/index.html.erb
<h4>Biometric</h4>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Weight</th>
      <th>Bmi</th>
      <th>Note</th>
      <th>Time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @biometrics.each do |biometric| %>
      <tr>
        <td><%= biometric.date %></td>
        <td><%= biometric.weight %></td>
        <td><%= biometric.bmi %></td>
        <td><%= biometric.note %></td>
        <td><%= biometric.time %></td>
        <td><%= link_to 'Show', biometric_path(biometric) %></td>
        <td><%= link_to 'Edit', edit_biometric_path(biometric) %></td>
        <td><%= link_to 'Destroy', biometric_path(biometric), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button class="btn">
<%= link_to 'New Biometric', new_biometric_path %>
</button>

app/views/biometrics/new.html.erb
<h1>New biometric</h1>

<%= render 'form' %>

<%= link_to 'Back', biometrics_path %>

app/views/biometrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @biometric.date %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @biometric.weight %>
</p>

<p>
  <strong>Bmi:</strong>
  <%= @biometric.bmi %>
</p>

<p>
  <strong>Note:</strong>
  <%= @biometric.note %>
</p>

<p>
  <strong>Time:</strong>
  <%= @biometric.time %>
</p>

<%= link_to 'Edit', edit_biometric_path(@biometric) %> |
<%= link_to 'Back', biometrics_path %>