config/routes.rb
CycleTracker::Application.routes.draw do
  
  get "welcome/index"
  resources :biometrics
  resources :moods
  resources :sleeps
  resources :weight_trainings
  resources :strength_trainings
  resources :weight_trainnings
  resources :stairs
  resources :rides
  resources :recents
  resources :routines
 devise_for :users
  root to: 'welcome#index'

  
end

app/models/biometric.rb
class Biometric < ActiveRecord::Base
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :exercise_type
  belongs_to :routine
end

app/models/exercise_type.rb
class ExerciseType < ActiveRecord::Base
  has_many :exercises
end

app/models/mood.rb
class Mood < ActiveRecord::Base
end

app/models/recent.rb
class Recent < ActiveRecord::Base
  #attr_accessible :user_id
  #belongs_to :user
end

app/models/ride.rb
class Ride < ActiveRecord::Base
end

app/models/routine.rb
class Routine < ActiveRecord::Base
  has_many :exercises
end

app/models/sleep.rb
class Sleep < ActiveRecord::Base
end

app/models/stair.rb
class Stair < ActiveRecord::Base
end

app/models/strength_training.rb
class StrengthTraining < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
    #attr_accessible :email, :password, :password_confirmation, :remember_me,
    #:first_name, :last_name, :profile_name
end

app/models/weight_training.rb
class WeightTraining < ActiveRecord::Base
end

app/models/weight_trainning.rb
class WeightTrainning < ActiveRecord::Base
end

app/helpers/biometrics_helper.rb
module BiometricsHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/recents_helper.rb
module RecentsHelper
  
  def total_distance 
    distances = @recents.map &:distance
    distances.inject :+
  end
  
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sleeps_helper.rb
module SleepsHelper
end

app/helpers/stairs_helper.rb
module StairsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Health Tracker 2.0</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a href="#" class="brand">Health Tracker</a>
					<ul class="nav">
					<li><a href="#">Dash Board</a></li>
					<li> <%= link_to "Biometric", biometrics_path %></a></li>
					<li> <%= link_to "Weight Training", weight_trainings_path%></li>
					<li> <%= link_to "Strength Training", routines_path%></li>
					<li> <%= link_to "Stairs", stairs_path%></li>
					<li> <%= link_to "Cycling", recents_path %></li>
					<li> <%= link_to "Sleep", sleeps_path%></li>
					<li> <%= link_to "Mood", moods_path%></li>
					</ul>
			</div>
	    </div>
	</div>
	<% if current_user %>
		<p>
		  <strong>Name:</strong>
		<%= current_user.email %> 
		</p>
	
		<button class="btn btn-warning"><%= link_to "Log out", destroy_user_session_path, method: :delete %></button>
	<% else %>
	<button class="btn"><%= link_to "Log in", new_user_session_path %></button>
	<%end%>
	
<div class="container">
	<p class="notice"><%= notice %></p>
	<!--<p class="alert"><%= alert %></p>-->
	<%= yield %>
</div>

</body>
</html>